# Generated by Django 5.0.3 on 2024-03-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("endurance", "Endurance"),
                            ("strength", "Strength"),
                            ("flexibility", "Flexibility"),
                            ("balance", "Balance"),
                        ],
                        max_length=60,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
            ],
        ),
    ]
