# Generated by Django 5.0.3 on 2024-04-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="height",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
