# Generated by Django 5.0.3 on 2024-05-06 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_customuser_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="height",
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="weight",
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(20)]),
        ),
    ]
